---
title: Java 异常
date: 2022-11-15 17:20:22
permalink: /java/se/exception
categories:
  - java
tags:
  - java
---

::: note 序言

异常

::: right

2022-01-02 @ 钟楠

:::

## 一、异常的基本概念

>程序运行过程中出现的错误，称为异常

## 二、异常的层次结构

![image-20230102133550985](https://cdn.staticaly.com/gh/jinmunan/imgs@master/java/image-20230102133550985.png)

### 1、异常的分类

>Error:错误：一旦发送错误，程序就会终止运行
>
>ExceptionSubClass：编译时异常：编写代码时就要处理的异常，抛出或声明
>
>RunTimeException：运行时异常：程序在运行过程中产生的异常

![image-20230102133601243](https://cdn.staticaly.com/gh/jinmunan/imgs@master/java/image-20230102133601243.png)

### 2、编译时异常

> 编译时异常需要手动捕获或者手动声明

```java
public class ExceptionDemo03 {
    public static void main(String[] args) {
        //对IO操作有可能会导致文件找不到的情况，需要手动捕获异常或者抛出异常
        /*FileInputStream fis = new FileInputStream("test.txt");*/
    }
}
```

### 3、运行时异常

> 运行时异常不需要手动捕获或者手动声明

```java
public class ExceptionDemo03 {
    public static void main(String[] args) {
        int i = 1/0;
    }
}
```

## 三、异常的处理程序

### 1、try、catch和finally

>try里是出现异常的代码块
>
>catch可以捕获异常
>
>finally一定会执行，一般用于释放资源,如果try中代码块导致jvm退出，finally就不会执行
>
>getMessage()取得异常描述信息
>
>printStackTrace()取得异常的堆栈信息

```java
try {
    可能产生的代码块
}catch(Exception e) {
    捕获异常的处理
}finally {
    最终一定会执行
}
```

```java
public class ExceptionDemo02 {
    public static void main(String[] args) {
        int i1 = 100;
        int i2 = 0;
        //try里是出现异常的代码
        try {
            //手动创造异常,出现异常后下面的语句不会执行
            int i3 = i1 / i2;
            //永远不会执行
            System.out.println(i3);
            //采用 catch 可以拦截异常
        } catch (Exception e) {
            //getMessage()取得异常描述信息
            System.out.println("被0除了+" + e.getMessage());
            //printStackTrace()取得异常的堆栈信息
            e.printStackTrace();
        } finally {
            System.out.println("一定会执行，一般用于释放资源");
        }
    }
}
```

### 2、手动捕获异常

```java
public class ExceptionDemo04 {
    public static void main(String[] args) {
        try {
            FileInputStream fis = new FileInputStream("test.txt");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }
}
```

### 3、手动声明异常

> 手动声明异常，调用者必须捕获异常，不捕获就交给jvm处理

```java
public class ExceptionDemo05 {
    public static void main(String[] args) throws Exception {
        FileInputStream fis = new FileInputStream("test.txt");
    }
}
```

### 4、finally

```java
public class ExceptionDemo08 {
    public static void main(String[] args) {
        int a = ExceptionDemo08.method();
        System.out.println(a);//10
    }

    public static int method() {
        int a = 10;
        try {
            return a;
        } finally {
            a = 100;
            System.out.println(a);//100
        }
    }
}
```

### 5、final、finally、finalize区别

#### 5.1、final

>final修饰的类无法继承
>
>final修饰的方法无法覆盖
>
>final修饰的变量不能重新赋值
>
>final修饰的对象不能改变引用地址

#### 5.2、finally

>finally语句块中的代码不管是否出现异常,都是必须执行的
>finally语句块的作用一般是释放资源

#### 5.3、finalize

>是Object类中的一个方法
>
>这个方法是由垃圾回收器GC负责调用的

### 6、手动抛出异常

> throw相当于return，下面不能再写代码

```java
public class ExceptionDemo09 {
    public static void main(String[] args) {
        try {
            int ret = method1(1000, 10);
            System.out.println(ret);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private static int method1(int value1, int value2) {
        if (value2 == 0) {
            throw new IllegalArgumentException("除数为 0");
        }
        if (!(value1 > 0 && value1 <= 100)) {
            throw new IllegalArgumentException("被除数必须为 1~100 之间的数据");
        }
        return value1 / value2;
    }
}
```

### 7、异常的捕获顺序

> 异常的捕获顺序是：从小到大

```java
public class ExceptionDemo10 {
    public static void main(String[] args) {
        FileInputStream fis = null;
        try {
            fis = new FileInputStream("test.txt");
            //异常的截获一般按照由小到大的顺序，也就是先截获子异常，再截获父异常
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (fis != null) {
                    fis.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

## 四、自定义异常

### 1、自定义编译期异常

```java
public class ExceptionDemo11 {
    public static void main(String[] args) {
        try {
            //调用方法时需要拦截异常并处理，不然就声明交给jvm来处理
            method1(10, 0);
        } catch (MyException01 e) {
            System.out.println(e.getMessage());
        }
    }
    //如果是编译时异常必须声明
    private static void method1(int value1, int value2) throws MyException01 {
        if (value2 == 0) {
            throw new MyException01("除数为 0");
        }
    }
}

//自定义编译时异常
class MyException01 extends Exception {
    public MyException01() {
        //调用父类的默认构造函数
        super();
    }

    public MyException01(String message) {
        //手动调用父类的构造方法
        super(message);
    }
}
```

### 2、自定义运行期异常

```java
public class ExceptionDemo12 {
    public static void main(String[] args) {
        method1(10, 0);
    }

    private static void method1(int value1, int value2) {
        if (value2 == 0) {
            //抛出运行时异常
            throw new MyException02("除数为0");
        }
    }
}


//自定义运行时异常
class MyException02 extends RuntimeException {
    public MyException02() {
        //调用父类的默认构造函数
        super();
    }

    public MyException02(String message) {
        //手动调用父类的构造方法
        super(message);
    }
}
```

## 五、异常继承机制

>子类方法不能抛出比父类方法更多的异常，但可以抛出父类方法异常的子异常

```java
class UserNotFoundException extends Exception {
}

class PasswordFailureException extends Exception {
}

class MyException03 extends UserNotFoundException {
}

interface UserManager {
    public void login(String username, String password) throws UserNotFoundException;
}

class UserManagerImpl1 implements UserManager {
    public void login(String username, String password) throws UserNotFoundException {
    }
}

/*class UserManagerImpl2 implements UserManager {
    public void login(String username, String password) throwsUserNotFoundException,PasswordFailureException {

    }
}*/

class UserManagerImpl3 implements UserManager {
    public void login(String username, String password) throws UserNotFoundException, MyException03 {
    }
}

public class ExceptionDemo13 {
    public static void main(String[] args) {
    }
}
```

